package com.linli.blackcatnews

/**
 * Android-specific implementation using BuildConfig.DEBUG
 * This will automatically use the debug flag set by Android Gradle Plugin
 *
 * Note: The BuildConfig class is generated by the Android Gradle Plugin
 * and contains build configuration fields.
 */
actual val isDebug: Boolean = BuildConfig.DEBUG